stages:
  - test

image: golang:1.13-alpine

test:unit:
  stage: test
  script:
  - apk add --update build-base
  - make unittest

test:integration:
  stage: test
  services:
  - name: registry.gitlab.com/soerenschneider/mountebank-docker
    alias: mountebank
  variables:
    SSHNOT_MOUNTEBANK: "mountebank:8080"
  script:
  - apk add --update build-base curl
  - curl -X POST --data @mountebank/ip-api.json mountebank:2525/imposters
  - make integrationtest
